name: dart_anki
description: Anki parser and manipulation library for dart
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 archive: ^3.1.2
 sqlite3: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
