name: dart_anki
description: Anki parser and manipulation library for dart
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
 archive: ^3.1.2
 freezed_annotation: ^2.4.1
 sqlite3: ^2.3.0

dev_dependencies:
  build_runner: ^2.0.1
  freezed: ^2.4.6
  pedantic: ^1.9.0
  test: ^1.14.4
